/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsconfig = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:4598d8ba-8750-4c43-bb32-1b68a14005af",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_IGIwfVVlF",
    "aws_user_pools_web_client_id": "7fk7kdu23h02a1n8c18fu15ira",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ltu2pl6uxjhefphy3w5h2jynh4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsconfig;
